title: A Place to look back
description: A place to put out my thoughts and experience to refer/look back on
author: Ganesh Halthota
github: https://github.com/ganesh737
about: I'm a Systems Engineer working on Embedded SoftWare Update Solutions
disqus_shortname: 
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/ganesh_"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ganesh-halthota/"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/3387741/ganesh737"
    - icon: fa-github
      link: "https://github.com/ganesh737"

share:
  twitter_username: "#"
  fb_appid: "#"

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://ganesh737.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
